name: Bygg KonCEPT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bygg-pdf:
    name: 'Bygg bok'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checka ut'
        uses: actions/checkout@v3
      - name: 'Installera'
        run: |
          sudo apt-get -q update
          sudo apt-get -q -y install texlive \
            texlive-lang-european texlive-science \
            texlive-fonts-recommended texlive-fonts-extra \
            texlive-extra-utils texlive-luatex \
            latexmk \
            language-pack-sv
      - name: 'Sätt systemspråk till svenska'
        run: |
          sudo locale-gen sv_SE.UTF-8
          sudo localectl set-locale LANG="sv_SE.UTF-8"
      - name: 'Kopiera hash'
        run: echo ${{ github.sha }} | cut -c1-7 > SHA.txt
      - name: 'Kopiera info om repository'
        run: |
          echo $GITHUB_SHA | cut -c1-7 > SHA.tmp
          echo $GITHUB_REF_NAME > branch.tmp
      - name: 'Bygg'
        run: make koncept.epub
      - name: 'Beräkna checksumma'
        run: sha256sum koncept.epub
      - name: 'Byt namn'
        run: mv koncept.epub koncept.$(cat VERSION.txt)+b${{ github.run_id }}.$(cat SHA.txt).epub
      - name: 'Skapa rapporter'
        run: |
          make images_linked
          make images_unlinked
          make TODOs
      - name: 'Ladda upp artefakt'
        uses: actions/upload-artifact@v3
        with:
          name: koncept-bok
          path: |
            koncept*.pdf
            koncept*.epub
          retention-days: 31
      - name: 'Ladda upp rapporter'
        uses: actions/upload-artifact@v3
        with:
          name: koncept-rapporter
          path: |
            images_linked.txt
            images_unlinked.txt
            TODOs.txt
