name: Bygg KonCEPT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testa-latex:
    name: 'Testa LaTeX'
    continue-on-error: true
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checka ut koden'
        uses: actions/checkout@v3
      - name: 'Installera Ubuntu-paket'
        run: |
          sudo apt-get --quiet update
          sudo apt-get --quiet --assume-yes --verbose-versions install \
            chktex
      - name: 'Kör test'
        run: chktex -v1 -n8 -n24 -n32 --output chktex.log koncept.tex
        # n8  eftersom det är fel tankstreckslängd för svenska.
        # n24 eftersom KonCEPT har använder index vid styckets början, inte vid tecken.
        # n32 eftersom det är fel citationstecken för svenska.
      - name: 'Skriv ut fel'
        run: grep -F 'Error' chktex.log >> $GITHUB_STEP_SUMMARY
  bygg-pdf:
    name: 'Bygg bok'
    needs: testa-latex
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checka ut koden'
        uses: actions/checkout@v3
      - name: 'Installera Ubuntu-paket'
        run: |
          sudo apt-get --quiet update
          sudo apt-get --quiet --assume-yes --verbose-versions install texlive \
            texlive-lang-european texlive-science \
            texlive-fonts-recommended texlive-fonts-extra \
            language-pack-sv
      - name: 'Sätt systemspråk till svenska'
        run: |
          sudo locale-gen sv_SE.UTF-8
          sudo localectl set-locale LANG="sv_SE.UTF-8"
      - name: 'Kopiera info om repository till filer'
        run: |
          echo $GITHUB_SHA | cut -c1-7 > SHA.tmp
          echo $GITHUB_REF_NAME > branch.tmp
      - name: 'Bygg koncept.pdf'
        run: make koncept.pdf
      - name: 'Lägg till versionsinformation i filnamnet'
        run: mv koncept.pdf koncept.$(cat VERSION.txt)+b${{ github.run_id }}.$(cat SHA.tmp).pdf
      - name: 'Visa checksumma'
        run: echo "<pre>$(sha256sum *.pdf)</pre>" >> $GITHUB_STEP_SUMMARY
      - name: 'Skapa rapporter'
        run: |
          echo "<pre>$(sed -n '1p' koncept.log)</pre>" >> $GITHUB_STEP_SUMMARY
          echo "| Statistik om koden | Antal |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          make images_linked
          echo "| Bildfiler med referenser | $(cat images_linked.txt | wc -l) |" >> $GITHUB_STEP_SUMMARY
          make images_unlinked
          echo "| Bildfiler utan referenser | $(cat images_unlinked.txt | wc -l) |" >> $GITHUB_STEP_SUMMARY
          make TODOs
          echo "| TODO-kommentarer | $(cat TODOs.txt | wc -l) |" >> $GITHUB_STEP_SUMMARY
          make long_lines
          echo "| Kodrader längre än 80 tecken | $(cat long_lines.txt | wc -l) |" >> $GITHUB_STEP_SUMMARY
      - name: 'Spara PDF-artefakt'
        uses: actions/upload-artifact@v3
        with:
          name: koncept-pdf
          path: koncept*.pdf
      - name: 'Spara rapporter'
        uses: actions/upload-artifact@v3
        with:
          name: rapporter
          path: |
            images_linked.txt
            images_unlinked.txt
            TODOs.txt
            long_lines.txt
